config/routes.rb
Rails.application.routes.draw do
  root 'meals#new'
  resources :recipes
  resources :meals
  get 'recipes/list/:id' => 'recipes#list'
  post 'recipes/import' => 'recipes#import'

end

app/models/meal.rb
class Meal < ActiveRecord::Base
 	validates :name, presence: true
	has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :meal
	has_many :steps
	accepts_nested_attributes_for :steps, :reject_if => :all_blank, allow_destroy: true
	validates :name, presence: true

	# Need to figure out what to do about steps with zero time specified 
	def self.nyt_import(url)
		require 'open-uri'
		page = Nokogiri::HTML(open(url))
		steps_array = page.css('ol.recipe-steps li')
		
		recipe_title = page.css('h1.recipe-title').text.strip
		recipe = Recipe.create(name: recipe_title)
		
		step_number = 0 
		ingredients_array = page.css('ul.recipe-ingredients li')
		ingredients_array.each do |ingredient|
			text = ingredient.text.strip
			if ingredient_prep_required?(text)
				recipe.steps.create(order_in_recipe: step_number, active: true, time: 4, description: "Prepare " + text) 
				step_number += 1
			end  
		end 
		steps_array.each do |step|
			time = recipe.find_step_time(step.text)
			recipe.steps.create(order_in_recipe: step_number, active: false, time: time, description: step.text)
			step_number += 1
		end 
		
		recipe 
	end 

	def find_step_time(step_text)
		
		if index = step_text.index("minutes")
			time_text = step_text[index-9..index+7]
			step_time = time_text[/\d+/].to_i 
		elsif index = step_text.index("hours")
			time_text = step_text[index-9..index+5]
			step_time = time_text[/\d+/].to_i * 60
		else 
			0
		end 
	end 

	def self.ingredient_prep_required?(ingredient_text)
		active_words = ["chopped", "sliced", "diced", "peeled", "minced", "cleaned", "grated", "mashed", "smashed", "juiced", "quartered"]
		if active_words.any? { |word| ingredient_text.include?(word) }
			return true 
		else 
			return false 
		end 

	end 
end

app/models/step.rb
class Step < ActiveRecord::Base
	belongs_to :recipe
	validates :order_in_recipe, uniqueness: { scope: :recipe_id,
    message: "each order should be unique" }

#note: above validator for :order_in_recipe doesn't actually work!!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
	def index
		@meals = Meal.all
	end
	
	def new
		@meal = Meal.new
	end

	def create
		@meal = Meal.new(meal_params)

		if @meal.save
			redirect_to @meal
		else
			render :new
		end
	end

	def show

		@meal = Meal.find(params[:id])
		
		first = Step.all.select { |step| step.recipe_id == @meal.recipe01 }
		second = Step.all.select { |step| step.recipe_id == @meal.recipe02 }

		if first.count > second.count
			a = first.collect { |step| [step.active, step.id, step.description, Recipe.find(step.recipe_id).name] }
			b = second.collect { |step| [step.active, step.id, step.description, Recipe.find(step.recipe_id).name] }
		else
			b = first.collect { |step| [step.active, step.id, step.description, Recipe.find(step.recipe_id).name] }
			a = second.collect { |step| [step.active, step.id, step.description, Recipe.find(step.recipe_id).name] }
		end

		merged_array = []

	    until a.empty?
			step = a.shift
				if step[0] == true
			    	merged_array << step
			    else
			    	merged_array << step
			    	loop do
			        	break if b.empty?
			        	b_step = b.shift
			        	if b_step[0] == true
			          	merged_array << b_step
			        	else
			          	merged_array << b_step
			          	break
			        	end
			      	end
			    end
		end
		@list = merged_array
	end


  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy
    redirect_to meals_path
  end

end

private
  def meal_params
    params.require(:meal).permit(:name, :recipe01, :recipe02)
  end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
  	@recipes = Recipe.all
  end

  def show
  	@recipe = Recipe.find(params[:id])
  	@steps = @recipe.steps
  end

  def list
    @recipe = Recipe.find(params[:id])
    @steps = @recipe.steps
  end  
  
  def new
  	@recipe = Recipe.new
  end

  def import

    recipe = Recipe.nyt_import(params[:url])
    redirect_to recipe
  end 

  def create
	@recipe = Recipe.new(recipe_params)
		#conditional to prevent saving non-unique order_in_recipe for a step - throw them in an array and check for dupes
    if @recipe.save
			redirect_to @recipe
		else
			render :new
		end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end


end

private
  def recipe_params
    params.require(:recipe).permit(:name, steps_attributes: [:id, :description, :active, :recipe_id, :order_in_recipe, :time, :_destroy])
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breakfast Factory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%# mega-container for the whole page begins%>
<div class="container">

	<%# navbar begins%>
	<nav class="navbar">

		<%# mobile menu link %>
		<div class="text-center">
			<a role="button" class="hidden-md hidden-lg" id="mobile-menu-link" data-toggle="collapse" data-target="#mobile-menu">
				MENU
			</a> 
		</div>

		<%# mobile menu %>
		<div class="collapse hidden-md hidden-lg" id="mobile-menu">
	    	<ul class="nav nav-stacked text-center">
		        <li> <%= link_to 'All Meals', meals_path %></li>
		        <li role="separator" class="divider"></li>
				<li> <%= link_to 'All Recipes', recipes_path %></li> 
		        <li role="separator" class="divider"></li>
				<li> <%= link_to 'Create a Meal', new_meal_path %></li> 
		        <li role="separator" class="divider"></li>
				<li> <%= link_to 'Add a Recipe', new_recipe_path %></li>
	    	</ul>
		</div> 

		<%# desktop menu %>
		<div class="hidden-xs hidden-sm" id="desktop-menu">
	    	<ul class="nav navbar-nav navbar-right">
		        <li> <%= link_to 'All Meals', meals_path %></li>
		        <li role="separator" class="divider"></li>
				<li> <%= link_to 'All Recipes', recipes_path %></li> 
		        <li role="separator" class="divider"></li>
				<li> <%= link_to 'Create a Meal', new_meal_path %></li> 
		        <li role="separator" class="divider"></li>
				<li> <%= link_to 'Add a Recipe', new_recipe_path %></li>
	    	</ul>
		</div> 

		<%# mobile logo %>

		<%# desktop logo %>

	<%# navbar ends%>
	</nav>


<%# page-specific content begins %>
			<%= yield %>
<%# page-specific content ends %>

<%# mega-container for the whole page ends%>
</div>

</body>


</html>

app/views/meals/_form.html.erb
<%= form_for @meal do |f| %>
  <div class="input-group">	
  		<%= f.label :meal_name, class: 'input-group-addon' %>
  		<%= f.text_field :name, class: 'form-control' %>
  </div>
  <br>
  <div class="input-group">	
	    <%= f.label :recipe_1, class: 'input-group-addon' %>
	    <%= f.collection_select(:recipe01, Recipe.all, :id, :name) %>
  </div>
  <br>
  <div class="input-group">
		<%= f.label :recipe_2, class: 'input-group-addon' %>
		<%= f.collection_select(:recipe02, Recipe.all, :id, :name) %>
  </div>
  <br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/meals/index.html.erb
<% @meals.each do |meal| %>
<li><%= link_to meal.name, meal_path(meal) %></li>
<% end %>

app/views/meals/new.html.erb
<h2>Select the recipes for your meal</h2>

<%= render 'form'%>

app/views/meals/show.html.erb
<h1>
<%= @meal.name %>: <%= link_to Recipe.find(@meal.recipe01).name, recipe_path(@meal.recipe01) %> & <%= link_to Recipe.find(@meal.recipe02).name, recipe_path(@meal.recipe02) %>
</h1>

<% @list.each do |step| %>
<%= step[3] %>: <%= step[2] %> (<%= step[0]%>)<br>
<% end %>
    
<br>
<%= link_to 'Delete Meal', meal_path(@meal), method: :delete %>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.label :recipe_name %> 
  <%= f.text_field :name %>
  <br><br>
  	<%= f.fields_for :steps do |step| %>
  	<% @recipe.steps.build %>
  		<% render 'step_fields', f: step %>
   	<% end %>
<%= link_to_add_association 'Add a step', f, :steps, 'data-association-insertion-node' => "this", 'data-association-insertion-method' => "before" %>
<br><br>
<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/recipes/_step_fields.html.erb
<div class="control-group nested-fields">
<%= f.label :order, class: 'input-group-addon' %>
<%= f.select(:order_in_recipe, 1..20) %>

<%= f.label :type, class: 'input-group-addon' %>
<%= f.select(:active, [['Active', true], ['Passive', false]]) %>

<%= f.label :description, class: 'input-group-addon' %>
<%= f.text_area :description, class: 'form-control' %>

<%= f.label :time, class: 'input-group-addon' %>
<%= f.select(:time, 1..60) %>

	<%= link_to_remove_association "Remove Step", f %>
</div>

app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>
<li><%= link_to recipe.name, recipe_path(recipe) %></li>
<% end %>

app/views/recipes/list.html.erb
<h1>
<%= @recipe.name %>
</h1>

<% @steps.each do |step| %>
	<% step.time.times do %>
	<%= step.description %>
	<br>
	<% end %>
	<br>
	<% end %>

<br>
<%= link_to 'Delete Recipe', recipe_path(@recipe), method: :delete %>

app/views/recipes/new.html.erb
<h2>Add all the steps for your meal</h2>
<%= render 'form'%>

<br><br>
<%= form_tag("/recipes/import", method: "post", class: "form-inline") do %>

  <%= label_tag(:url, "Import from url:") %>
  <%= text_field_tag(:url,nil, class: 'form-control') %>
  <%= submit_tag("Import", class: 'btn btn-primary' ) %>
<% end %>

app/views/recipes/show.html.erb
<h1>
<%= @recipe.name %>
</h1>

<% @steps.each do |step| %>
	<%= step.order_in_recipe %>. <%= step.description %>
	<br>
	<% end %>

<br>
<%= link_to 'Delete Recipe', recipe_path(@recipe), method: :delete %>